package golog

import (
	"fmt"
	"time"
)

// The log event struct provides just that, structure for a log messages. 
// LogEvents are generated by golog. 
type logEvent struct {
    // The time a log message was received. 
	timestamp time.Time
    // The level of the log message. 
	level     LogLevel
    // The message templated used to render the displayed log message. 
	message   string
    // Optional properties to add to your structured logs. 
    // Properties can include complex objects, simply strings, any
	props     properties
}

// Properties to use in a structured log event. 
type properties map[string]any

// Renders a message as a string. 
// The format interface is used to generate a string from a log event
type FormatMessage interface {
	RenderMessage() string
}

func (e *logEvent) RenderMessage() string {
	return fmt.Sprintf("[%s %v] %s", e.level.ToString(), e.timestamp.Format("2006-01-02T15:04:05"), e.message)
}
